//
//  MainViewControllerConstants.h
//  tottepost
//
//  Created by ISHITOYA Kentaro on 11/12/22.
//  Copyright (c) 2011 cocotomo. All rights reserved.
//

#define MAINVIEW_STATUS_BAR_HEIGHT 20.0
#define MAINVIEW_SETTING_BUTTON_PADDING 10.0
#define MAINVIEW_SETTING_BUTTON_WIDTH 32.0
#define MAINVIEW_COMMENT_BUTTON_PADDING 10.0
#define MAINVIEW_COMMENT_BUTTON_WIDTH 37.0
#define MAINVIEW_CAMERA_BUTTON_WIDTH 112.0
#define MAINVIEW_CAMERA_BUTTON_HEIGHT 39.0
#define MAINVIEW_TOOLBAR_HEIGHT 54.0
#define MAINVIEW_PROGRESS_HEIGHT 30.0
#define MAINVIEW_PROGRESS_WIDTH 100.0
#define MAINVIEW_PROGRESS_PADDING_X 10.0
#define MAINVIEW_PROGRESS_PADDING_Y 50.0
#define MAINVIEW_PADDING_Y 10.0
#define MAINVIEW_COMMENT_VIEW_WIDTH_FOR_IPHOEN 250.0
#define MAINVIEW_COMMENT_VIEW_HEIGHT_FOR_IPHONE 60
#define MAINVIEW_COMMENT_VIEW_WIDTH_FOR_IPAD 400.0
#define MAINVIEW_COMMENT_VIEW_HEIGHT_FOR_IPAD 140
#define MAINVIEW_SMALL_ICON_WIDTH 16
#define MAINVIEW_INDICATOR_HEIGHT 20
#define MAINVIEW_INDICATOR_PADDING_Y 5
#define TOTTEPOST_PROGRESS_REMOVE_DELAY 3
#define MAINVIEW_POST_BUTTON_WIDTH 80
#define MAINVIEW_POSTCANCEL_BUTTON_WIDTH 80
