/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"

#import "Types.h"
#import "Errors.h"

enum EDAMSponsoredGroupRole {
  SponsoredGroupRole_GROUP_MEMBER = 1,
  SponsoredGroupRole_GROUP_ADMIN = 2,
  SponsoredGroupRole_GROUP_OWNER = 3
};

@interface EDAMPublicUserInfo : NSObject <NSCoding> {
  EDAMUserID __userId;
  NSString * __shardId;
  int __privilege;
  NSString * __username;

  BOOL __userId_isset;
  BOOL __shardId_isset;
  BOOL __privilege_isset;
  BOOL __username_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=userId, setter=setUserId:) EDAMUserID userId;
@property (nonatomic, retain, getter=shardId, setter=setShardId:) NSString * shardId;
@property (nonatomic, getter=privilege, setter=setPrivilege:) int privilege;
@property (nonatomic, retain, getter=username, setter=setUsername:) NSString * username;
#endif

- (id) init;
- (id) initWithUserId: (EDAMUserID) userId shardId: (NSString *) shardId privilege: (int) privilege username: (NSString *) username;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (EDAMUserID) userId;
- (void) setUserId: (EDAMUserID) userId;
#endif
- (BOOL) userIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) shardId;
- (void) setShardId: (NSString *) shardId;
#endif
- (BOOL) shardIdIsSet;

#if !__has_feature(objc_arc)
- (int) privilege;
- (void) setPrivilege: (int) privilege;
#endif
- (BOOL) privilegeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) username;
- (void) setUsername: (NSString *) username;
#endif
- (BOOL) usernameIsSet;

@end

@interface EDAMPremiumInfo : NSObject <NSCoding> {
  EDAMTimestamp __currentTime;
  BOOL __premium;
  BOOL __premiumRecurring;
  EDAMTimestamp __premiumExpirationDate;
  BOOL __premiumExtendable;
  BOOL __premiumPending;
  BOOL __premiumCancellationPending;
  BOOL __canPurchaseUploadAllowance;
  NSString * __sponsoredGroupName;
  int __sponsoredGroupRole;

  BOOL __currentTime_isset;
  BOOL __premium_isset;
  BOOL __premiumRecurring_isset;
  BOOL __premiumExpirationDate_isset;
  BOOL __premiumExtendable_isset;
  BOOL __premiumPending_isset;
  BOOL __premiumCancellationPending_isset;
  BOOL __canPurchaseUploadAllowance_isset;
  BOOL __sponsoredGroupName_isset;
  BOOL __sponsoredGroupRole_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=currentTime, setter=setCurrentTime:) EDAMTimestamp currentTime;
@property (nonatomic, getter=premium, setter=setPremium:) BOOL premium;
@property (nonatomic, getter=premiumRecurring, setter=setPremiumRecurring:) BOOL premiumRecurring;
@property (nonatomic, getter=premiumExpirationDate, setter=setPremiumExpirationDate:) EDAMTimestamp premiumExpirationDate;
@property (nonatomic, getter=premiumExtendable, setter=setPremiumExtendable:) BOOL premiumExtendable;
@property (nonatomic, getter=premiumPending, setter=setPremiumPending:) BOOL premiumPending;
@property (nonatomic, getter=premiumCancellationPending, setter=setPremiumCancellationPending:) BOOL premiumCancellationPending;
@property (nonatomic, getter=canPurchaseUploadAllowance, setter=setCanPurchaseUploadAllowance:) BOOL canPurchaseUploadAllowance;
@property (nonatomic, retain, getter=sponsoredGroupName, setter=setSponsoredGroupName:) NSString * sponsoredGroupName;
@property (nonatomic, getter=sponsoredGroupRole, setter=setSponsoredGroupRole:) int sponsoredGroupRole;
#endif

- (id) init;
- (id) initWithCurrentTime: (EDAMTimestamp) currentTime premium: (BOOL) premium premiumRecurring: (BOOL) premiumRecurring premiumExpirationDate: (EDAMTimestamp) premiumExpirationDate premiumExtendable: (BOOL) premiumExtendable premiumPending: (BOOL) premiumPending premiumCancellationPending: (BOOL) premiumCancellationPending canPurchaseUploadAllowance: (BOOL) canPurchaseUploadAllowance sponsoredGroupName: (NSString *) sponsoredGroupName sponsoredGroupRole: (int) sponsoredGroupRole;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) currentTime;
- (void) setCurrentTime: (EDAMTimestamp) currentTime;
#endif
- (BOOL) currentTimeIsSet;

#if !__has_feature(objc_arc)
- (BOOL) premium;
- (void) setPremium: (BOOL) premium;
#endif
- (BOOL) premiumIsSet;

#if !__has_feature(objc_arc)
- (BOOL) premiumRecurring;
- (void) setPremiumRecurring: (BOOL) premiumRecurring;
#endif
- (BOOL) premiumRecurringIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) premiumExpirationDate;
- (void) setPremiumExpirationDate: (EDAMTimestamp) premiumExpirationDate;
#endif
- (BOOL) premiumExpirationDateIsSet;

#if !__has_feature(objc_arc)
- (BOOL) premiumExtendable;
- (void) setPremiumExtendable: (BOOL) premiumExtendable;
#endif
- (BOOL) premiumExtendableIsSet;

#if !__has_feature(objc_arc)
- (BOOL) premiumPending;
- (void) setPremiumPending: (BOOL) premiumPending;
#endif
- (BOOL) premiumPendingIsSet;

#if !__has_feature(objc_arc)
- (BOOL) premiumCancellationPending;
- (void) setPremiumCancellationPending: (BOOL) premiumCancellationPending;
#endif
- (BOOL) premiumCancellationPendingIsSet;

#if !__has_feature(objc_arc)
- (BOOL) canPurchaseUploadAllowance;
- (void) setCanPurchaseUploadAllowance: (BOOL) canPurchaseUploadAllowance;
#endif
- (BOOL) canPurchaseUploadAllowanceIsSet;

#if !__has_feature(objc_arc)
- (NSString *) sponsoredGroupName;
- (void) setSponsoredGroupName: (NSString *) sponsoredGroupName;
#endif
- (BOOL) sponsoredGroupNameIsSet;

#if !__has_feature(objc_arc)
- (int) sponsoredGroupRole;
- (void) setSponsoredGroupRole: (int) sponsoredGroupRole;
#endif
- (BOOL) sponsoredGroupRoleIsSet;

@end

@interface EDAMAuthenticationResult : NSObject <NSCoding> {
  EDAMTimestamp __currentTime;
  NSString * __authenticationToken;
  EDAMTimestamp __expiration;
  EDAMUser * __user;
  EDAMPublicUserInfo * __publicUserInfo;

  BOOL __currentTime_isset;
  BOOL __authenticationToken_isset;
  BOOL __expiration_isset;
  BOOL __user_isset;
  BOOL __publicUserInfo_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=currentTime, setter=setCurrentTime:) EDAMTimestamp currentTime;
@property (nonatomic, retain, getter=authenticationToken, setter=setAuthenticationToken:) NSString * authenticationToken;
@property (nonatomic, getter=expiration, setter=setExpiration:) EDAMTimestamp expiration;
@property (nonatomic, retain, getter=user, setter=setUser:) EDAMUser * user;
@property (nonatomic, retain, getter=publicUserInfo, setter=setPublicUserInfo:) EDAMPublicUserInfo * publicUserInfo;
#endif

- (id) init;
- (id) initWithCurrentTime: (EDAMTimestamp) currentTime authenticationToken: (NSString *) authenticationToken expiration: (EDAMTimestamp) expiration user: (EDAMUser *) user publicUserInfo: (EDAMPublicUserInfo *) publicUserInfo;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) currentTime;
- (void) setCurrentTime: (EDAMTimestamp) currentTime;
#endif
- (BOOL) currentTimeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) authenticationToken;
- (void) setAuthenticationToken: (NSString *) authenticationToken;
#endif
- (BOOL) authenticationTokenIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) expiration;
- (void) setExpiration: (EDAMTimestamp) expiration;
#endif
- (BOOL) expirationIsSet;

#if !__has_feature(objc_arc)
- (EDAMUser *) user;
- (void) setUser: (EDAMUser *) user;
#endif
- (BOOL) userIsSet;

#if !__has_feature(objc_arc)
- (EDAMPublicUserInfo *) publicUserInfo;
- (void) setPublicUserInfo: (EDAMPublicUserInfo *) publicUserInfo;
#endif
- (BOOL) publicUserInfoIsSet;

@end

@protocol EDAMUserStore <NSObject>
- (BOOL) checkVersion: (NSString *) clientName : (int16_t) edamVersionMajor : (int16_t) edamVersionMinor;  // throws TException
- (EDAMAuthenticationResult *) authenticate: (NSString *) username : (NSString *) password : (NSString *) consumerKey : (NSString *) consumerSecret;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMAuthenticationResult *) refreshAuthentication: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMUser *) getUser: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMPublicUserInfo *) getPublicUserInfo: (NSString *) username;  // throws EDAMNotFoundException *, EDAMSystemException *, EDAMUserException *, TException
- (EDAMPremiumInfo *) getPremiumInfo: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
@end

@interface EDAMUserStoreClient : NSObject <EDAMUserStore> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface EDAMUserStoreProcessor : NSObject <TProcessor> {
  id <EDAMUserStore> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithUserStore: (id <EDAMUserStore>) service;
- (id<EDAMUserStore>) service;
@end

@interface EDAMUserStoreConstants : NSObject {
}
+ (int16_t) EDAM_VERSION_MAJOR;
+ (int16_t) EDAM_VERSION_MINOR;
@end
